### ISSUE TITLE
Custom Exceptions

### ISSUE THREAD

**Issue by cjtu** [cjtu/craterpy#5]
Replace current exceptions like "ValueError" or "ImportError" with custom exceptions defined in a file called exceptions.py. They should have useful names and inherit from the Exception they replace

**Comment by cxong** [comment]
Please list which exceptions should be customised. I guess https://github.com/cjtu/craterpy/blob/2699930d9973277550c8462e9937a620db55b89d/craterpy/stats.py#L43 is a no-brainer but in other cases (e.g. raise ValueError if lat/long out of range) the built-in exceptions should be fine.

Custom exceptions should be used if they should be handled in a special way, e.g. a library may provide its own exception base class so that users can catch any exception raised by said library. I'm not sure that applies to this project.

**Comment by cjtu** [comment]
Good point, wrapping base Exceptions is a little overkill. I left some comments on (#7). It looks like a custom import error is the only one I can forsee us needing right now until I think more a library catch-all. Thanks for your comments
